# Generated by Django 5.0.3 on 2024-03-31 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(null=True, upload_to='profile_photos/'),
        ),
    ]
