# Generated by Django 5.0.3 on 2024-03-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('SINGLE', 'Одиночный'), ('GROUP', 'Групповой')]),
        ),
    ]
