# Generated by Django 5.0.3 on 2024-03-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_chat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(null=True, upload_to='chat_files/'),
        ),
    ]
