# Generated by Django 4.2.5 on 2024-04-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_customuser_bio'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
